chore(git-*): update script for git-* and ldapsearch
Signed-off-by: marslo <marslo.jiao@gmail.com>

diff --git a/itool/git-stat b/itool/git-stat
--- a/itool/git-stat
+++ b/itool/git-stat
@@ -1,26 +1,46 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2086,SC2124
+# shellcheck source=/dev/null disable=SC2086,SC2124,SC2155
+#=============================================================================
+#     FileName : git-stat
+#       Author : marslo
+#      Created : 2025-02-15 19:45:31
+#   LastChange : 2026-02-12 23:34:05
+#=============================================================================
 
-# usage:
-# $ git stats --author="marslo" --after="2022-01-01"
-# .. files changed : 1046
-# .. lines inserted : 14096
-# .. lines deleted : 8871
+# USAGE:
+# # show help
+# $ git stat -h or $ git stat -- --help
+#
+# $ git stat --author "marslo" -l -- --after='2025-01-01'
+# statistics for marslo - git@github.com:marslo/ibook.git :
+#
+# line changes :
+#
+#   files changed ......................... 100% ( 57/57 )
+#   line inserted ......................... 100% ( 2089/2089 )
+#   line deleted  ......................... 100% ( 462/462 )
 
 shopt -s extglob
 
-# credit belongs to https://raw.githubusercontent.com/ppo/bash-colors/master/bash-colors.sh
-# shellcheck disable=SC2015,SC2059
-c() { [ $# == 0 ] && printf "\e[0m" || printf "$1" | sed 's/\(.\)/\1;/g;s/\([SDIUFNHT]\)/2\1/g;s/\([KRGYBMCW]\)/3\1/g;s/\([krgybmcw]\)/4\1/g;y/SDIUFNHTsdiufnhtKRGYBMCWkrgybmcw/12345789123457890123456701234567/;s/^\(.*\);$/\\e[\1m/g'; }
+declare -r HERE="$( dirname "${BASH_SOURCE[0]:-$0}" )"
+declare -r ME="$(basename "${BASH_SOURCE[0]:-$0}" | tr '-' ' ')"
+
+# @credit: https://github.com/ppo/bash-colors
+# @usage:  or copy & paste the `c()` function from:
+#          https://github.com/ppo/bash-colors/blob/master/bash-colors.sh#L3
+# shellcheck disable=SC2015
+test -f "${HERE}/bash-colors.sh" && source "${HERE}/bash-colors.sh" || { c() { :; }; }
+
+function die() { echo -e "$(c R)ERROR$(c) : $*" >&2; exit 2; }
 function exitOnError() { if [ $? -ne 0 ]; then echo -e "$(c R)ERROR$(c) : $*" >&2; exit 1; fi; }
-function showHelp() { echo -e "${usage}"; exit 0; }
+function showHelp() { echo -e "${USAGE}"; exit 0; }
 function isRepo() { git rev-parse --git-dir >/dev/null 2>&1 || exitOnError 'not a git repo !'; }
 function trim() { IFS='' read -r str; echo "${str}" | sed -e 's/^[[:blank:]]*//;s/[[:blank:]]*$//'; }
 function padRight() {
   while IFS=':' read -r param value length; do
     if [[ -n "${param}" ]] && [[ -n "${value}" ]]; then
       padlength=${length:-40}
-      pad=$(printf '\x2e%.0s' $(seq "${padlength}"))
+      pad=$( printf '\x2e%.0s' $(seq "${padlength}") )
       printf "%s%s%s\n" "${param}" "${pad:${#param}}" "${value}"
     else
       printf "%s:%s\n" "${param}" "${value}"
@@ -29,148 +49,166 @@ function padRight() {
 }
 
 function debugLog(){
-  local pad=true
-  case "$1" in --np | --no-pad ) pad=false; shift ;; esac
-  # shellcheck disable=SC2155
-  local str=$(echo -e "$@" | awk '{print "[DEBUG] >> " $0}')
-
-  echo -e "$(c W)${str}$(c)" | padRight
-  # if [[ true = "${pad}" ]]; then
-  #   # shellcheck disable=SC2046,SC2027
-  # else
-  #   # shellcheck disable=SC2046
-  #   echo -e "$(c W)${str}$(c)"
-  # fi
+  case "$1" in --np | --no-pad ) pad=false; shift;; esac
+  local str=$( echo -e "$@" | awk '{print "[DEBUG] >> " $0}' )
+  echo -e "$(c Wid)${str}$(c)" | padRight
 }
 
 function lineChangesStat() {
   local allChanges
   local userChanges
   local debugInfo
-  allChanges=$(git log --shortstat --oneline --format=tformat: ${GIT_OPT} |
-          awk '{ files+=$1; inserted+=$4; deleted+=$6 } END { print files, inserted, deleted }')
-  userChanges=$(git log --shortstat --oneline --author=${author} --format=tformat: ${GIT_OPT} |
-          awk '{ files+=$1; inserted+=$4; deleted+=$6 } END { print files, inserted, deleted }')
+  local -a cmd=( git log --shortstat --oneline --format=tformat: )
+
+  allChanges=$("${cmd[@]}" "${GIT_OPT[@]}" |
+               awk '{ files+=$1; inserted+=$4; deleted+=$6 } END { print files, inserted, deleted }'
+              )
+  userChanges=$("${cmd[@]}" "${GIT_OPT[@]}" --author="${author}" |
+                awk '{ files+=$1; inserted+=$4; deleted+=$6 } END { print files, inserted, deleted }'
+               )
 
   echo -e "\n$(c M)line changes$(c) :\n"
-  if [[ true = "${verbose}" ]]; then
+  if "${verbose}"; then
     debugInfo=$(echo "${allChanges} ${userChanges}" |
-                       awk '{ files=$1; inserted=$2; deleted=$3; userFiles=$4; userInserted=$5; userDeleted=$6 } END \
-                            {
-                              printf( "ALL CHANGES\\n" )
-                              printf( "\tfiles changed : %s\\n" , files        )
-                              printf( "\tline inserted : %s\\n" , inserted     )
-                              printf( "\tline deleted : %s\\n"  , deleted      )
-                              printf( "USER CHANGES\\n" )
-                              printf( "\tfiles changed : %s\\n" , userFiles    )
-                              printf( "\tline inserted : %s\\n" , userInserted )
-                              printf( "\tline deleted : %s"     , userDeleted  )
-                            }'
+                awk '{ files=$1; inserted=$2; deleted=$3; userFiles=$4; userInserted=$5; userDeleted=$6 } END \
+                     {
+                       printf( "ALL CHANGES\\n" )
+                       printf( "\tfiles changed : %s\\n" , files        )
+                       printf( "\tline inserted : %s\\n" , inserted     )
+                       printf( "\tline deleted : %s\\n"  , deleted      )
+                       printf( "USER CHANGES\\n" )
+                       printf( "\tfiles changed : %s\\n" , userFiles    )
+                       printf( "\tline inserted : %s\\n" , userInserted )
+                       printf( "\tline deleted : %s"     , userDeleted  )
+                     }'
               )
     debugLog "${debugInfo}"
+    echo ""
   fi
 
-  echo -e "${allChanges} ${userChanges}" |
-           awk '{
-                  userFiles=$4; userInserted=$5; userDeleted=$6; fileRate=$4*100/$1; insertRate=$5*100/$2; deleteRate=$6*100/$3
-                } END {
-                  printf( "\tfiles changed : %s ( %s% ) \n" , userFiles    , fileRate   )
-                  printf( "\tline inserted : %s ( %s% ) \n" , userInserted , insertRate )
-                  printf( "\tline deleted : %s ( %s% ) \n"  , userDeleted  , deleteRate )
-                }' |
-           padRight
+  echo "${allChanges} ${userChanges}" |
+       awk '{
+              files=$1; inserted=$2; deleted=$3; userFiles=$4; userInserted=$5; userDeleted=$6; fileRate=$4*100/$1; insertRate=$5*100/$2; deleteRate=$6*100/$3
+            } END {
+              printf( "\tfiles changed : %7.4f%% ( %d/%d ) \n" , fileRate   , userFiles    , files    )
+              printf( "\tline inserted : %7.4f%% ( %d/%d ) \n" , insertRate , userInserted , inserted )
+              printf( "\tline deleted  : %7.4f%% ( %d/%d ) \n" , deleteRate , userDeleted  , deleted  )
+            }' |
+       padRight
 }
 
 function commitsCount() {
   local allCount
   local userCount
   local debugInfo
+  local -a cmd=( git shortlog -s -n )
 
-  allCount=$(git shortlog -s -n ${GIT_OPT} | awk '{ sum += $1; } END { print sum; }')
-  userCount=$(git shortlog -s -n ${GIT_OPT} --author=${author} | awk '{print $1}')
+  allCount=$( "${cmd[@]}" "${GIT_OPT[@]}" | awk '{ sum += $1; } END { print sum; }' )
+  userCount="$( "${cmd[@]}" "${GIT_OPT[@]}" --author="${author}" | awk '{sum += $1} END {print sum}' )"
 
   echo -e "\n$(c M)commits$(c) :\n"
-  if [[ true = "${verbose}" ]]; then
+  if "${verbose}"; then
     debugInfo=$(echo -e "${allCount} ${userCount}" |
-                       awk '{ aCount=$1; uCount=$2 } END \
-                            { printf( "COMMITS\\n" )
-                              printf( "\tall commit : %s\\n"  , aCount )
-                              printf( "\tuser commit : %s" , uCount )
-                            }'
+                awk '{ aCount=$1; uCount=$2 } END \
+                     { printf( "COMMITS\\n" )
+                       printf( "\tall commit : %s\\n"  , aCount )
+                       printf( "\tuser commit : %s" , uCount )
+                     }'
               )
     debugLog "${debugInfo}"
+    echo ""
   fi
 
   echo -e "${allCount} ${userCount}" |
-           awk '{ aCount=$1; uCount=$2; countRate=$2*100/$1; } END \
-                { printf( "\tcommit submitted : %s ( %s% ) \n", uCount, countRate ) }' |
-           padRight
+  awk '{ aCount=$1; uCount=$2; countRate=$2*100/$1; } END \
+       { printf( "\tcommit submitted : %7.4f%% ( %d/%d ) \n" , countRate, uCount, aCount ) }' |
+  padRight
 }
 
+# main
 declare verbose=false
-declare allStats=false
 declare lineChanges=false
 declare commitsCount=false
-declare GIT_OPT
+declare -a GIT_OPT=()
+declare author="$( git config --get user.name )"
+declare -r USAGE="NAME
+  $(c Cs)${ME}$(c) - to get git statistic for line-changes and commit count
 
-usage="""
-\t $(c R)git-stat$(c) - to get git statistic for line-changes and commit count
-\nSYNOPSIS:
-\n\t$(c sY)\$ git stat [ -h | --help ]
-\t\t   [ -v | --verbose | --debug ]
-\t\t   [ -a | --all ]
-\t\t   [ -l | --line-change ]
-\t\t   [ -c | --commit-count ]
-\t\t   [ -u | --user | --account <account> ]
-\t\t   [ -- <GIT_OPT> ]$(c)
-\nEXAMPLE:
-\n\tshow help
-\t\t$(c G)\$ git stat -h$(c) | $(c G)\$ git stat --help$(c)
-\n\tget verbose
-\t\t$(c G)\$ git stat -v$(c) | $(c G)\$ git stat --verbose$(c) | $(c G)\$ git stat --debug$(c)
-\n\tto list all statistic for current user
-\t\t$(c G)\$ git stat -a$(c)
-\n\tto list line changes for current user since 1 month ago
-\t\t$(c G)\$ git stat --line-change -- --since='1 month ago'$(c)
-\n\tto list line-changes statistic for particular account
-\t\t$(c G)\$ git stat -l -u <account>$(c) | $(c G)\$ git stat --line-change --account <account>$(c)
-\n\tto list statistic for current user with specific GIT_OPT
-\t\t$(c G)\$ git stat -- --after='2022-01-01' --before='2023-01-01'$(c)
-\t\t$(c G)\$ git stat -- --since='2 weeks 3 days 2 hours 30 minutes 59 seconds ago'$(c)
-"""
+SYNOPSIS
+  $(c sY)\$ ${ME} $(c 0Wi)[ OPTIONS ]$(c)
+
+OPTIONS
+  $(c G)-a$(c), $(c G)--all$(c)                       show all statistic $(c i)( line-changes and commit count )$(c)
+  $(c G)-l$(c), $(c G)--lc$(c), $(c G)--line-change$(c)         show line-changes statistic
+  $(c G)-c$(c), $(c G)--cc$(c), $(c G)--commit-count$(c)        show commit count
+  $(c G)-u$(c), $(c G)--user$(c), $(c G)--author$(c) $(c Ci)<account>$(c)  specify the account to get statistic for $(c 0i)( default: $(c 0Ci)\$(git config user.name)$(c 0i) )$(c)
+  $(c Cs)--$(c) $(c Mi)<GIT_OPT>$(c)                    specify GIT_OPT to filter statistic
+                                  $(c Wdi)# e.g. $(c 0Cs)-- $(c 0Mi)--since='1 month ago'$(c) or $(c 0Cs)-- $(c 0Mi)--after='2022-01-01'$(c 0Wdi) etc.$(c)
+  $(c G)-h$(c), $(c G)--help$(c)                      show this help message and exit
+  $(c G)-v$(c), $(c G)--verbose$(c), $(c G)--debug$(c)          show statistic with more details
+
+EXAMPLE
+  $(c Wdi)# to list all statistic for $(c 0Wi)current user$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)-a$(c)
+
+  $(c Wdi)# to list line changes for $(c 0Wi)current user $(c 0Wdi)since 1 month ago$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)--line-change $(c 0Csi)-- $(c 0Mi)--since='1 month ago'$(c)
+
+  $(c Wdi)# to list line-changes statistic for $(c 0Wi)particular account$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)-l -u $(c 0Ci)<account>$(c) | $(c Y)\$ ${ME} $(c 0Gi)--line-change --account $(c 0Ci)<account>$(c)
+
+  $(c Wdi)# to list statistic for $(c 0Wi)current user $(c 0Wdi)with specific GIT_OPT$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)-a $(c 0Csi)-- $(c 0Mi)--after='2022-01-01' --before='2023-01-01'$(c)
+  $(c Y)\$ ${ME} $(c 0Gi)-l --verbose $(c 0Csi)-- $(c 0Mi)--since='2 weeks 3 days 2 hours 30 minutes 59 seconds ago'$(c)
+
+TIPS
+  $(c 0Wi)\`\`\`bash
+  $(c 0Wdi)# for macOS$(c)$(c 0Wi)
+  \$ brew install gawk && sudo ln -sf /usr/local/bin/gawk /usr/local/bin/awk
+  \$ export PATH=\"/usr/local/bin:\$PATH\"
+  \`\`\`$(c)
+"
+
+[[ 0 = "$#" ]] && showHelp
 
 while test -n "$1"; do
   case "$1" in
-    -v | --verbose | --debug   ) verbose=true       ; shift   ;;
-    -u | --author  | --user    ) user="$2"          ; shift 2 ;;
-    -l | --lc | --line-change  ) lineChanges=true   ; shift   ;;
-    -c | --cc | --commit-count ) commitsCount=true  ; shift   ;;
-    -a | --all                 ) allStats=true      ; shift   ;;
-    --                         ) shift ; GIT_OPT=$@ ; break   ;;
-    -h | --help | *            ) showHelp                     ;;
+    -v | --verbose | --debug   ) verbose=true           ; shift   ;;
+    -u | --author  | --user    ) author="$2"            ; shift 2 ;;
+    -l | --lc | --line-change  ) lineChanges=true       ; shift   ;;
+    -c | --cc | --commit-count ) commitsCount=true      ; shift   ;;
+    -a | --all                 ) commitsCount=true;
+                                 lineChanges=true;        shift   ;;
+    -h                         ) showHelp                         ;;
+    --                         ) shift ;
+                                 case "$1" in
+                                   -h | --help ) showHelp         ;;
+                                   *           ) GIT_OPT=("$@")   ;;
+                                 esac; break                      ;;
+    *                          ) die "invalid option : '$*'"      ;;
   esac
 done
 
-declare author="${user:-$(git config --get user.name)}"
-if [[ true = "${allStats}" ]]; then
+isRepo
+# show all statistic if no specific statistic type is specified == -a | --all
+{ ! "${lineChanges}" && ! "${commitsCount}"; } && {
   lineChanges=true
   commitsCount=true
-fi
+}
 
-isRepo
-echo -e "statistics for $(c Y)${author}$(c) - $(c G)$(git config --get remote.origin.url)$(c) :"
+printf "statistics for $(c Csi)%s$(c) - $(c Gi)%s$(c) :\n" "${author}" "$(git config --get remote.origin.url)"
 
-if [[ true = "${verbose}" ]]; then
+"${verbose}" && {
   debugLog "PARAMS"
   debugLog "\tverbose      : ${verbose}     "
-  debugLog "\tGIT_OPT      : ${GIT_OPT}     "
+  debugLog "\tGIT_OPT      : ${GIT_OPT[*]}  "
   debugLog "\tauthor       : ${author}      "
   debugLog "\tlineChanges  : ${lineChanges} "
   debugLog "\tcommitsCount : ${commitsCount}"
   echo ''
-fi
+}
 
-[[ true = "${lineChanges}"  ]] && lineChangesStat
-[[ true = "${commitsCount}" ]] && commitsCount
+"${lineChanges}"  && lineChangesStat
+"${commitsCount}" && commitsCount
 
-# vim: ft=sh ts=2 sts=2 sw=2 et
+# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:
diff --git a/itool/ldapsearch b/itool/ldapsearch
--- a/itool/ldapsearch
+++ b/itool/ldapsearch
@@ -1,68 +1,106 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC1078,SC1079
+# shellcheck source=/dev/null disable=SC1078,SC1079
+#=============================================================================
+#     FileName : ldapsearch
+#       Author : marslo
+#      Created : 2023-01-06 21:49:44
+#   LastChange : 2026-02-20 15:28:39
+#=============================================================================
 
 shopt -s extglob
 
-c() {
-  # shellcheck disable=SC1009,SC2015,SC2028
-  [ $# -eq 0 ] && echo "\033[0m" || echo "$1" | sed -E "s/(.)/‹\1›/g;s/([KRGYBMCW])/3\1/g;s/([krgybmcw])/4\1/g;s/S/22/;y/sufnKRGYBMCWkrgybmcw›/14570123456701234567m/;s/‹/\\\033[/g";
+# shellcheck disable=SC2155
+declare -r HERE="$( dirname "${BASH_SOURCE[0]:-$0}" )"
+# @credit: https://github.com/ppo/bash-colors
+# @usage:  or copy & paste the `c()` function from:
+#          https://github.com/ppo/bash-colors/blob/master/bash-colors.sh#L3
+# shellcheck disable=SC2015
+test -f "${HERE}/bash-colors.sh" && source "${HERE}/bash-colors.sh" || { c() { :; }; }
+
+usage="""SYNOPSIS
+  $(c Ys)\$ ldapsearch $(c 0Mi)<USER_ID> $(c 0Wd)[ $(c 0Ci)FIELD $(c 0Wd)[ $(c 0Ci)FIELD $(c 0Wd)[ $(c 0Ci)FIELD $(c 0Wd)] ] ] [ $(c 0G)OPTION $(c 0Wd)]$(c)
+
+OPTIONS
+  $(c G)-h, --help$(c)    Show this help message and exit.
+
+EXAMPLE
+  $(c Wdi)# get help$(c)
+  $(c Y)\$ ldapsearch $(c 0G)-h$(c)
+
+  $(c Wdi)# get all information for $(c 0Wi)<USER_ID>$(c)
+  $(c Y)\$ ldapsearch $(c 0Mi)<USER_ID>$(c)
+
+  $(c Wdi)# get only DN for $(c 0Wi)<USER_ID>$(c)
+  $(c Y)\$ ldapsearch $(c 0Mi)<USER_ID> $(c 0Ci)dn$(c)
+
+  $(c Wdi)# get multiple FIELD for $(c 0Wi)marslo$(c)
+  $(c Y)\$ ldapsearch $(c 0Mi)marslo $(c 0Ci)dn memberOf displayName givenName sAMAccountName$(c)
+
+TIPS
+  $(c Gi)\`\`\`bash
+  $(c 0Wdi)# for macOS users$(c 0Gi)
+  \$ brew install gun-sed openldap
+  \`\`\`$(c)"""
+
+# shellcheck disable=SC2181
+function exitOnError() { if [ $? -ne 0 ]; then echo -e "$1.\nExiting."; exit 1; fi; }
+function help() { echo -e "${usage}"; exit 0; }
+function passToken() { pass show "${1}" | head -n1; }
+function escape_ere() { "${SED}" -E 's/[][(){}.^$*+?|\\]/\\&/g'; }
+# shellcheck disable=SC2155
+buildAttr() {
+  local -a _in=( "${@}" )
+  local _attr="$( printf '%s\n' "${_in[@]}" | escape_ere | paste -sd'|' - )"
+  printf '%s' "${_attr}"
 }
 
-usage="""TO SEARCH IN LDAP
-\nSYNOPSIS:
-\n\t$(c sY)\$ ldapsearch <userId> [ field [ field [ field ] ] ] [ -h | help ]$(c)
-\nExample:
-\n\tget help
-\n\t\t$(c G)\$ ldapsearch help$(c)
-\n\tget all information for <userId>
-\n\t\t$(c G)\$ ldapsearch <userId>$(c)
-\n\tget only DN for <userId>
-\n\t\t$(c G)\$ ldapsearch <userId> dn$(c)
-\n\tget both DN and memberOf for <userId>
-\n\t\t$(c G)\$ ldapsearch <userId> dn memberOf$(c)
-"""
+[[ 'Darwin' = "$(uname)" ]] && SED="$(brew --prefix gnu-sed)/libexec/gnubin/sed"     || SED='/usr/bin/sed'
+[[ 'Darwin' = "$(uname)" ]] && LDAPSEARCH="$(brew --prefix openldap)/bin/ldapsearch" || LDAPSEARCH='/usr/bin/ldapsearch'
 
-function exitOnError() {
-  # shellcheck disable=SC2181
-  if [ $? -ne 0 ]; then
-    echo -e "$1.\nExiting."
-    exit 1
-  fi
-}
+test -f "${SED}"        || { echo -e "$(c Rs)Error$(c 0Ri): $(c 0Gi)\`${SED}\` $(c 0Ri)not found.$(c)"; exit 1; }
+test -f "${LDAPSEARCH}" || { echo -e "$(c Rs)Error$(c 0Ri): $(c 0Gi)\`${LDAPSEARCH}\` $(c 0Ri)not found.$(c)"; exit 1; }
 
-function help() {
-  echo -e "${usage}"
-  exit 0
-}
-
-userId="$1"
-attributes=''
-# for mac
-SED='/usr/local/opt/gnu-sed/libexec/gnubin/sed'
-LDAPSEARCH='/usr/local/opt/openldap/bin/ldapsearch'
-sedOpt="${SED} -r '/^(#.*)$/d;/^\s*$/d'"
-
-if [[ $# -gt 1 ]]; then
-  attributes="$(echo "${@: -$(( $#-1 ))}" | cut -d' ' -f1-)"
-fi
-
-if [[ -n ${attributes} ]]; then
-  attr=${attributes//+( )/|}
-  sedOpt="${SED} -rn 's/^((${attr}):.*)$/\1/p'"
-fi
-
-if [ $# -eq 0 ] || [ "$1" = "help" ] || [ "$1" = '-h' ]; then
+if [ $# -eq 0 ] || [ "$1" = "--help" ]|| [ "$1" = "help" ] || [ "$1" = '-h' ]; then
   help
-else
-  command="""
-    ${LDAPSEARCH} -LLL \
-                  -o ldif-wrap=no \
-                  -x \
-                  -H ldaps://ldaps.domain.com:636 \
-                  -b 'dc=domain,dc=com' \
-                  -D <account> \
-                  -w <password> \
-                  CN=${userId} ${attributes} | ${sedOpt}
-  """
-  eval "${command}"
 fi
+
+declare userId=''
+declare -a attributes=()
+declare -a SED_OPT=( "${SED}" -r '/^(#.*)$/d;/^\s*$/d' )
+declare -a command=()
+declare -r account='account'
+declare -r ldasphost='ldaps://sldap.domain.com:636'
+declare -r basedn='dc=domain,dc=com'
+# shellcheck disable=SC2155
+declare -r password="$(passToken "devops/srvs/${account}")"
+
+[[ $# -eq 0 ]] && help
+while test -n "$1"; do
+  case "$1" in
+    -h | --help | help ) help ;;
+    -*                 ) echo -e "Error: Invalid option '$1'."; exit 1 ;;
+    *                  ) userId="$1"; shift;
+                         attributes+=( "${@}" ); break ;;
+  esac
+done
+
+[[ -z "${userId}" ]] && echo -e "Error: Missing required argument <userId>." && exit 1
+
+command+=( "${LDAPSEARCH}" -LLL )
+command+=( -o ldif-wrap=no )
+command+=( -x )
+command+=( -H "${ldasphost}" )
+command+=( -b "${basedn}" )
+command+=( -D "${account}" )
+command+=( -w "${password}" )
+command+=( CN="${userId}" )
+
+if [[ ${#attributes[@]} -gt 0 ]]; then
+  attr="$(buildAttr "${attributes[@]}")"
+  SED_OPT=( "${SED}" -rn "s/^((${attr}):.*)$/\1/p" )
+  command+=( "${attributes[@]}" )
+fi
+
+"${command[@]}" | "${SED_OPT[@]}"
+
+# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:
